---
- name: Configure the Raspberry Pi after RetroPie install
  hosts: retropie
  
  tasks:
    - name: Download the retropie-automation artifacts
      git:
        repo: 'https://github.com/NRieker/retropie-ansible.git'
        depth: 1
        dest: /home/pi/retropie-ansible
        force: yes
  
    - name: Copy RetroArch joypad configurations
      copy:
        src: /home/pi/retropie-ansible/joypads/autoconfig/
        dest: /opt/retropie/configs/all/retroarch/autoconfig/
        force: yes
        mode: '0755'

    - name: Copy Mupen64Plus joypad configurations
      copy:
        src: /home/pi/retropie-ansible/joypads/mupen64plus/InputAutoCfg.ini
        dest: /opt/retropie/configs/n64/InputAutoCfg.ini
        force: yes
        mode: '0755'

    - name: Copy Emulationstation joypad configurations
      copy:
        src: /home/pi/retropie-ansible/joypads/emulationstation/es_input.cfg
        dest: /opt/retropie/configs/all/emulationstation/es_input.cfg
        force: yes
        mode: '0755'

    - name: Copy cloud save runcommand-onend script
      copy:
        src: /home/pi/retropie-ansible/scripts/runcommand-onend.sh
        dest: /opt/retropie/configs/all/runcommand-onend.sh
        force: yes
        mode: '0755'

    - name: Copy cloud save force restore script to runcommand-menu
      copy:
        src: /home/pi/retropie-ansible/scripts/save_file_force_restore.sh
        dest: /opt/retropie/configs/all/runcommand-menu/
        force: yes
        mode: '0755'
        
    - name: Add cloud save auto restore script to rc.local
      become: yes
      lineinfile:
        path: /etc/rc.local
        state: present
        insertbefore: '^exit 0'
        line: '/bin/su -c "/home/pi/retropie-ansible/scripts/save_file_auto_restore.sh" pi'
        
    - name: Create saves directory
      file:
        path: /home/pi/RetroPie/saves
        state: directory
        mode: '0755'
        
    - name: Create states directory
      file:
        path: /home/pi/RetroPie/states
        state: directory
        mode: '0755'
        
    - name: Change save file directory
      lineinfile:
        path: /opt/retropie/configs/all/retroarch.cfg
        state: present
        regexp: 'savefile_directory'
        line: 'savefile_directory = "/home/pi/RetroPie/saves"'
        
    - name: Change save state directory
      lineinfile:
        path: /opt/retropie/configs/all/retroarch.cfg
        state: present
        regexp: 'savestate_directory'
        line: 'savestate_directory = "/home/pi/RetroPie/states"'
...
