---
- name: Configure the Raspberry Pi after RetroPie install
  hosts: retropie
  
  tasks:
    - name: Copy RetroArch joypad configurations
      copy:
        src: /home/pi/retropie-automation/joypads/autoconfig/
        dest: /opt/retropie/configs/all/retroarch/autoconfig/
        force: yes

    - name: Copy Mupen64Plus joypad configurations
      copy:
        src: /home/pi/retropie-automation/joypads/mupen64plus/InputAutoCfg.ini
        dest: /opt/retropie/configs/n64/InputAutoCfg.ini
        force: yes

    - name: Copy Emulationstation joypad configurations
      copy:
        src: /home/pi/retropie-automation/joypads/emulationstation/es_input.cfg
        dest: /opt/retropie/configs/all/emulationstation/es_input.cfg
        force: yes

...