---
- name: Setup the Raspberry Pi for RetroPie install
  hosts: all

  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

    - name: Disable overscan
      become: yes
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'disable_overscan'
        line: 'disable_overscan=1'

    - name: Enable hdmi force hotplug
      become: yes
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'hdmi_force_hotplug'
        line: 'hdmi_force_hotplug=1'

    - name: Set GPU memory to 128 MB
      become: yes
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'gpu_mem'
        line: 'gpu_mem=128'
      
    - name: Ensure autologin.conf is present
      become: yes
      file:
        path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
        owner: root
        group: root
        mode: '0644'
        state: touch
        
    - name: Enable autologin
      become: yes
      blockinfile:
        path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
        state: present
        block: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin pi --noclear %I $TERM

    - name: Install git
      become: yes
      apt:
        name: git
        state: present
        force_apt_get: yes

    - name: Install rclone
      become: yes
      apt:
        name: rclone
        state: present
        force_apt_get: yes

    - name: Download the latest RetroPie-Setup script
      git:
        repo: 'https://github.com/RetroPie/RetroPie-Setup.git'
        depth: 1
        dest: /home/pi/RetroPie-Setup
        force: yes
...                                            
