---
- name: Update packages and edit config.txt
  hosts: retropie-ansible
  remote_user: pi
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

    - name: Disable overscan
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'disable_overscan'
        line: 'disable_overscan=1'

    - name: Enable hdmi force hotplug
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'hdmi_force_hotplug'
        line: 'hdmi_force_hotplug=1'

    - name: Set GPU memory to 128 MB
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'gpu_mem'
        line: 'gpu_mem=128'

    - name: Enable autologin
      blockinfile:
        path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
        state: present
        create: yes
        owner: root
        mode: '0644'
        block: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin pi --noclear %I $TERM
    
- name: Prepare for RetroPie installation
  hosts: retropie-ansible
  remote_user: pi

    - name: Install git
      become: yes
      apt:
        name: git
        state: present
        force_apt_get: yes

    - name: Download the latest RetroPie-Setup script
      git:
        repo: 'https://github.com/RetroPie/RetroPie-Setup.git'
        depth: 1
        dest: /home/pi/RetroPie-Setup
        force: yes
...