---
- name: Setup the Raspberry Pi for RetroPie install
  hosts: retropie

  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

    - name: Disable overscan
      become: yes
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'disable_overscan'
        line: 'disable_overscan=1'

    - name: Enable hdmi force hotplug
      become: yes
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'hdmi_force_hotplug'
        line: 'hdmi_force_hotplug=1'

    - name: Set GPU memory to 128 MB
      become: yes
      lineinfile:
        path: /boot/config.txt
        state: present
        regexp: 'gpu_mem'
        line: 'gpu_mem=128'

    - name: Install git
      apt:
        name: git
        state: present
        force_apt_get: yes

    - name: Install the latest rclone client
      command:
        cmd: curl https://rclone.org/install.sh | sudo bash
        warn: no

    - name: Download the RetroPie-Setup script
      git:
        repo: 'https://github.com/RetroPie/RetroPie-Setup.git'
        depth: 1
        dest: /home/pi/RetroPie-Setup
        force: yes

    - name: Download the retropie-automation artifacts
      git:
        repo: 'https://github.com/NRieker/retropie-automation.git'
        depth: 1
        dest: /home/pi/retropie-automation
        force: yes
...                                            
